server:
  port: ${APPLICATION_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: kozak127

apple:
  topic:
    input: input
    output: output